baseURL       = "http://vesta.1gb.ru/"
languageCode  = "ru"
title         = "ВЕСТА"
theme         = "roxo"
summarylength = 25
publishDir = "docs"

# Site Menus
[menu]
  # Navbar Menus
#  [[menu.nav]]
#    name    = "Домашняя"
#    url     = ""
#    weight  = 1
  [[menu.nav]]
    name    = "О нас"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Новости"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Контакты"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Связаться с нами"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "2 January 2006"
  dateFormatFull = "02/01/2006"
  dateFormatTime = "2 Jan 2006 15:04"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/hero.jpg"
    heading               = "ВЕСТА"
    tagline               = "УПРАВЛЯЮЩАЯ КОМПАНИЯ"
    primary_button        = "Наши услуги"
    primary_button_url    = "portfolio"
    secondary_button      = "Связаться с нами"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "НОВОСТИ И ОБЪЯВЛЕНИЯ"
    subtitle  = ""

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Контакты"
      address = "165302, Архангельская область, Котлас, улица Володарского, 106"
      phone   = "+78183752873"
      email   = "Upravdompluskotlas@yandex.ru"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Карта сайта"
        [[params.footer.sitemap.link]]
          name = "О нас"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Новости"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Контакты"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Связаться с нами"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Социальные сети"
        [[params.footer.social.link]]
          name = "VK"
          url  = "#"
        [[params.footer.social.link]]
          name = "Telegram"
          url  = "#"
        [[params.footer.social.link]]
          name = "YouTube"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = ""
        description = ""